repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types:
          - svg
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        additional_dependencies: ['prettier']

  - repo: local
    hooks:
      - id: ts-lint-fix
        name: Run lint:fix
        entry: pnpm lint:fix
        language: system
        files: '\.(ts|tsx)$'
      - id: prettier-format
        name: Format code with Prettier
        entry: pnpm format
        language: system
